services:
  backend:
    container_name: portfolio-backend
    build:
      context: ../
      dockerfile: ./docker/dev.dockerfile
    command: npm run dev:watch
    volumes:
      - ../src:/usr/app/src
      - files_data:/usr/app/uploads
    ports:
      - 8000:8000
    depends_on:
      - sqldb
    environment:
      DATABASE_HOST: sqldb
      DATABASE_PORT: 5432
      DATABASE_NAME: portfolio_db
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: my_password
    restart: on-failure

  sqldb:
    container_name: portfolio-sqldb
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: "portfolio_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "my_password"
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure:10

volumes:
  postgres_data:
  files_data:
